modLoader="javafml" 
loaderVersion="[31,)" 
issueTrackerURL="https://github.com/VinnyStalck/EarthToJava/issues" 

[[mods]] 
    modId="earthtojava" 
    version="Pre-Alpha v1.0.0"
    displayName="Earth to Java" 
    displayURL="https://github.com/VinnyStalck/EarthToJava" 
    logoFile="" 
    credits="" 
    authors="VinnyStalck" 
    description='''
    Brings some of the features from Minecraft Earth mobile game to Minecraft Java Edition.
    '''
[[dependencies.earthtojava]] 
    modId="forge" 
    mandatory=true
    versionRange="[31,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.earthtojava]]
    modId="minecraft" 
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
